### PR TITLE
add vectorized behaviour to yearfrac function

### PR DESCRIPTION
**Pull request by fatkaratekid**
The function will return list as a result if any of the inputs are iterable. Also added some missing requirements. All tests and examples are also there.

### CODE REVIEW

**Review by ulf1 — APPROVED** [review]

**Comment by ulf1** [comment]
Sorry "Rename yearfrac.py to yearfrac - vectorized.py" was a merge mistake of mine

**Comment by ulf1** [comment]
What is the twisted package used for?

**Comment by ulf1** [comment]
Uploaded to PyPi as v0.4.0

https://pypi.org/project/yearfrac/0.4.0/

Thank You. 

I used "fatkaratekid" as your contributor name in the README. Let me know if you want to use a real name or another pseudonym.

Your coding looks really good. I will check your openmednlp projects. I still need some PR to secure a T-Shirt ;)

**Comment by fatkaratekid** [comment]
I used it as a test suite, so you might want to remove it if you want to
use something else. I am pretty agnostic, when it comes to that.

**Comment by fatkaratekid** [comment]
My pleasure.

You can use my real name if you want (in one of the next updates or
something). It is Ivan Nesic.

Needless to say, code can be faster, but then all the other functions need
to be vectorized. Not sure what the end goal is, so might be good enough.
Still, it would be a fun thing to do.

**Comment by ulf1** [comment]
`yearfrac` has the scope to calculate the time difference in years. Should be straightforward but there are different rules or methods to do that. 

I just uploaded the `panelctmc` package where `yearfrac` is used for preprocessing the dates. In other words, the results are annual values. In this case annual transition probabilities. See line 45 

https://github.com/kmedian/panelctmc/blob/master/panelctmc/panel_to_datalist.py

**Pull request merged**
